-- Seed data for Vedam Events Platform

INSERT INTO events (
  slug, title, subtitle, tagline, description, banner_url, event_type, mode, venue,
  start_date, end_date, seats, registrations_count, is_featured, status,
  speaker_data, schedule_data, learning_outcomes, benefits, who_should_attend,
  faq_data, testimonials_data, whatsapp_community_link, duration_minutes,
  page_config, meta_title, meta_description
) VALUES
(
  'genai-bootcamp',
  'GenAI Builder Bootcamp',
  'Build AI Products in 2 Days',
  'From zero to shipping your first AI product',
  'Join Vedam''s intensive GenAI Bootcamp where you''ll learn to build production-ready AI applications using the latest tools and frameworks. Hands-on coding, real projects, and mentorship from industry experts.',
  'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=600&fit=crop',
  'bootcamp',
  'hybrid',
  'Vedam Campus, Hyderabad',
  NOW() + INTERVAL '14 days',
  NOW() + INTERVAL '16 days',
  50,
  32,
  true,
  'published',
  '[
    {"name": "Dr. Rajesh Kumar", "designation": "AI Research Lead, Google", "bio": "15+ years in ML/AI with focus on generative models and production systems.", "photo": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop", "linkedin": "https://linkedin.com"},
    {"name": "Priya Sharma", "designation": "Founder, AI Startup", "bio": "Built and scaled 3 AI products. Y Combinator alum.", "photo": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop", "linkedin": "https://linkedin.com"}
  ]'::jsonb,
  '[
    {"time": "09:00 AM", "title": "Registration & Networking", "type": "break"},
    {"time": "10:00 AM", "title": "Introduction to GenAI Stack", "type": "session", "speaker": "Dr. Rajesh Kumar"},
    {"time": "12:00 PM", "title": "Lunch Break", "type": "break"},
    {"time": "01:00 PM", "title": "Building Your First AI App", "type": "session", "speaker": "Priya Sharma"},
    {"time": "03:00 PM", "title": "Networking & Demo", "type": "networking"}
  ]'::jsonb,
  '["Understand LLM fundamentals and prompt engineering", "Build a full-stack AI application", "Deploy AI products to production", "Master RAG and fine-tuning basics"]'::jsonb,
  '["Certificate of completion", "Access to Vedam AI community", "1-on-1 mentorship session", "Project portfolio piece"]'::jsonb,
  '["CS/AI students looking to build real projects", "Developers transitioning to AI", "Startup founders exploring AI products", "Tech professionals upskilling in GenAI"]'::jsonb,
  '[
    {"question": "Do I need prior AI experience?", "answer": "Basic programming knowledge is required. We cover AI fundamentals from scratch."},
    {"question": "What should I bring?", "answer": "Your laptop with Node.js and Python installed. We provide all other tools."},
    {"question": "Is food provided?", "answer": "Yes, lunch and refreshments are included for both days."}
  ]'::jsonb,
  '[
    {"name": "Arjun M.", "role": "B.Tech Student", "text": "Built my first AI chatbot in the bootcamp. Got an internship offer the next week!", "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop"},
    {"name": "Sneha K.", "role": "Software Engineer", "text": "Best hands-on AI workshop I have attended. Vedam''s approach is truly builder-first.", "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop"}
  ]'::jsonb,
  'https://chat.whatsapp.com/example-community',
  960,
  '[
    {"id": "hero", "type": "hero", "enabled": true, "order": 0},
    {"id": "about", "type": "about", "enabled": true, "order": 1},
    {"id": "speakers", "type": "speakers", "enabled": true, "order": 2},
    {"id": "schedule", "type": "schedule", "enabled": true, "order": 3},
    {"id": "who_should_attend", "type": "who_should_attend", "enabled": true, "order": 4},
    {"id": "faq", "type": "faq", "enabled": true, "order": 5},
    {"id": "testimonials", "type": "testimonials", "enabled": true, "order": 6},
    {"id": "registration", "type": "registration", "enabled": true, "order": 7}
  ]'::jsonb,
  'GenAI Builder Bootcamp | Vedam School of Technology',
  'Build production-ready AI applications in 2 days. Join Vedam''s intensive GenAI Bootcamp.'
),
(
  'ai-workshop',
  'AI Workshop: Prompt Engineering Masterclass',
  'Master the Art of AI Communication',
  'Write prompts that get extraordinary results',
  'A focused 4-hour workshop on advanced prompt engineering techniques used by top AI teams.',
  'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&h=600&fit=crop',
  'workshop',
  'online',
  'Zoom (link after registration)',
  NOW() + INTERVAL '7 days',
  NOW() + INTERVAL '7 days' + INTERVAL '4 hours',
  200,
  145,
  true,
  'published',
  '[]'::jsonb,
  '[]'::jsonb,
  '["Advanced prompt patterns", "Chain-of-thought techniques", "System prompt design"]'::jsonb,
  '["Workshop recording", "Prompt template library"]'::jsonb,
  '["Anyone using ChatGPT/Claude professionally"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  'https://chat.whatsapp.com/example-workshop',
  240,
  '[]'::jsonb,
  'AI Prompt Engineering Workshop | Vedam',
  'Master prompt engineering in 4 hours with Vedam experts.'
),
(
  'startup-masterclass',
  'Founder Talk: Building AI Startups',
  'Learn from Founders Who Built AI Companies',
  'Insider strategies from successful AI founders',
  'An exclusive masterclass featuring founders who have built and scaled AI startups from India.',
  'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&h=600&fit=crop',
  'masterclass',
  'online',
  'Live Stream',
  NOW() + INTERVAL '21 days',
  NOW() + INTERVAL '21 days' + INTERVAL '2 hours',
  500,
  89,
  false,
  'published',
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  NULL,
  120,
  '[]'::jsonb,
  'Founder Talk: AI Startups | Vedam',
  'Learn startup strategies from successful AI founders.'
);
